NUM_PLAYERS = 4
NUM_FINGERS = 5
NUM_ROUNDS = 5
POSSIBLE_FINGERS = [i for i in range(NUM_FINGERS + 1)]
POSSIBLE_AMOUNTS = [i for i in range(NUM_FINGERS * NUM_PLAYERS + 1)]
STATE_DIM = (NUM_PLAYERS - 1) * 2 
ACTION_DIM = POSSIBLE_FINGERS + POSSIBLE_AMOUNTS

if __name__ == '__main__':
    print(f'NUM_PLAYERS: {NUM_PLAYERS}')
    print(f'NUM_FINGERS: {NUM_FINGERS}')
    print(f'NUM_ROUNDS: {NUM_ROUNDS}')
    print(f'POSSIBLE_FINGERS: {POSSIBLE_FINGERS}')
    print(f'POSSIBLE_AMOUNTS: {POSSIBLE_AMOUNTS}')
    print(f'STATE_DIM: {STATE_DIM}')
    print(f'ACTION_DIM: {ACTION_DIM}')